# Generated by Django 5.1.2 on 2024-10-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_name', models.CharField(max_length=100)),
                ('events', models.TextField(blank=True, null=True)),
                ('notifications', models.CharField(max_length=255)),
            ],
        ),
    ]
