# Generated by Django 5.1.2 on 2024-10-29 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0001_initial'),
        ('tasks', '0004_rename_type_task_priority_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='events',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
