# Generated by Django 5.1.2 on 2024-10-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200, unique=True)),
                ('task_deadline', models.DateTimeField(verbose_name='due date')),
                ('priority_level', models.CharField(max_length=200)),
                ('recurring', models.BooleanField()),
                ('preparation', models.BooleanField()),
                ('how_much_prep', models.CharField(max_length=200)),
            ],
        ),
    ]
