# Generated by Django 5.1.2 on 2024-10-29 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='type',
            new_name='priority_level',
        ),
    ]
