# Generated by Django 5.1.4 on 2024-12-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='preparation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_deadline',
            field=models.DateTimeField(help_text='Must be in YYYY-MM-DD format', verbose_name='due date'),
        ),
    ]
