# Generated by Django 5.1.2 on 2024-10-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="aboutMe",
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phoneNumber",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="state",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="streetAddress",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
