# Generated by Django 5.1.2 on 2024-10-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0003_userprofile_aboutme_userprofile_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="aboutMe",
            field=models.CharField(max_length=500),
        ),
    ]
