# Generated by Django 5.1.2 on 2024-11-05 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_userprofile_aboutme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='aboutMe',
            new_name='about_me',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='streetAddress',
            new_name='street_address',
        ),
    ]
